// app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google"; // Import de la police
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import { AnalyticsProvider } from '@/app/_components/providers/AnalyticsProvider';
import { Toaster } from "@/app/_components/ui/sonner";
import { Analytics } from "@vercel/analytics/react"
import Script from "next/script"
import { ThemeProvider } from "next-themes";


const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Définir les poids
  variable: "--font-inter", // Définir une variable CSS pour la police
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang="fr" suppressHydrationWarning className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link rel="stylesheet" type='text/css' href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
        {/* Google Tag (gtag.js) - Chargé uniquement en production */}
        {process.env.NODE_ENV === 'production' && process.env.NEXT_PUBLIC_GA_ID && (
          <>
            <Script async src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GA_ID}`} />
            <Script
              dangerouslySetInnerHTML={{
                __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '${process.env.NEXT_PUBLIC_GA_ID}');
                `,
              }}
            />
            <meta name="google-site-verification" content="GJhiqE5sy7GitDAscpGr9OA8LPC68RSEzcXLP0WEldE" />
          </>
        )}
      </head>
      <body className="relative overflow-x-hidden">
        <div className="fixed inset-0 -z-20 bg-[rgb(248,248,248)] dark:bg-black" />

        <div aria-hidden className="pointer-events-none fixed inset-0 -z-10">
          <div className="absolute inset-0
            bg-[radial-gradient(circle_at_50%_0%,rgba(255,255,255,0.085),transparent_70%)]" />
          <div className="absolute inset-0
            bg-[radial-gradient(circle_at_80%_30%,rgba(255,255,255,0.045),transparent_60%)]" />
        </div>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AnalyticsProvider />
          <main>{children}</main>
          <Toaster richColors />
          <div className="pointer-events-none fixed bottom-0 left-0 right-0 h-[100px] z-10 bg-gradient-to-b from-[rgba(5,5,5,0)] to-black opacity-100">
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
